### ISSUE TITLE
Solver warning for large pack configurations

### ISSUE THREAD

**Issue by wigging** [pybamm-team/liionpack#17]
I tested the example shown below with the following pack configurations:

| Configuration | Elapsed time (min:sec) | Warnings |
|---|---|---|
| 16p2s (32 cells) | 0:08 | none |
| 32p10s (320 cells) | 1:21 | none |
| 32p20s (640 cells) | 3:56 | none |
| 16p40s (640 cells) | 3:49 | LinAlgWarning: Ill-conditioned matrix, X = solve(A, z).flatten() |
| 16p96s (1536 cells) | 18:43 | LinAlgWarning: Ill-conditioned matrix, X = solve(A, z).flatten() |

```python
import liionpack as lp
import matplotlib.pyplot as plt
import numpy as np
import pybamm

# Parameters
Np = 16
Ns = 40

# Generate the netlist
netlist = lp.setup_circuit(Np=Np, Ns=Ns, Rb=1e-4, Rc=1e-2, Ri=5e-2, V=3.2, I=80.0)

output_variables = [
    'X-averaged total heating [W.m-3]',
    'Volume-averaged cell temperature [K]',
    'X-averaged negative particle surface concentration [mol.m-3]',
    'X-averaged positive particle surface concentration [mol.m-3]'
]

# Heat transfer coefficients
nbatt = Np * Ns
htc = np.ones(nbatt) * 10
print('nbatt =', nbatt)

# Cycling protocol
protocol = lp.generate_protocol()

# PyBaMM parameters
chemistry = pybamm.parameter_sets.Chen2020
parameter_values = pybamm.ParameterValues(chemistry=chemistry)

# Solve pack
output = lp.solve(netlist=netlist,
                  parameter_values=parameter_values,
                  protocol=protocol,
                  output_variables=output_variables,
                  htc=htc)

plt.show()
```

The ill conditioned warnings are related to the `scipy.linalg.solve` function in `netlist_utils.py` which solves the electrical circuit for node voltage and battery current. The `A` matrix used by the solver for `X = solve(A, z).flatten()` appears to be a banded matrix. Therefore, it may be appropriate to use the `scipy.linalg.solve_banded` function to solve the system of equations representing the circuit. This may also improve the solution time of the pack simulation. But I'm not sure if all pack configurations would generate a banded `A` matrix for the circuit equations. The code may need to check if the configuration is suitable for the `scipy.linalg.solve` or for the `scipy.linalg.solve_banded` function.

**Comment by TomTranter** [comment]
Hey Gavin, thanks - there are plenty of other options for solving this matrix. Scipy was just the quickest and dirtiest - should also look into a sparse matrix implementation to speed things up. The simulation times you have there is probably increasing much more for the electrochemical models rather than the linalg. I'm guessing it doesn't fail right away either,  it might also be the current is very small for large packs especially in the rest periods where current is rebalancing.

**Comment by wigging** [comment]
The table below compares the original solver approach to the results for running the latest liionpack version which uses the sparse solver. I did not change the applied current in the example (`I = 80.0`) so it appears that the solver was causing the issue and not the current. @TomTranter You can close this issue unless you have more comments. Thanks for getting this implemented so quickly. 

| Configuration | Elapsed time (min:sec) <br> original solver | Elapsed time (min:sec) <br> sparse solver | Warnings |
|---|---:|---:|---:|
| 16p2s (32 cells) | 0:08 | 0:07 | none |
| 32p10s (320 cells) | 1:21 | 1:08 | none |
| 32p20s (640 cells) | 3:56 | 2:38 | none |
| 16p40s (640 cells) | 3:49 | 2:34 | none |
| 16p96s (1536 cells) | 18:43 | 9:12 | none |

**Comment by TomTranter** [comment]
That is really strange that it makes such a difference to the simulation time as I said only about 10% is spent on the circuit_solve. Maybe due to some tolerances it was returning bad values for the electrochemical sims and these were taking longer to converge in the mapped iterator... I'll close this issue but open a general profiling one. Maybe we can add more info for debug to the logger
